// <auto-generated />
using MammalAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MammalAPI.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20200430203629_InitialFakeWithSeed")]
    partial class InitialFakeWithSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MammalAPI.Models.FakeMammal", b =>
                {
                    b.Property<int>("FakeMammalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FakeMammalId");

                    b.ToTable("FakeMammal");

                    b.HasData(
                        new
                        {
                            FakeMammalId = 1,
                            Name = "Raninbow Whale"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
