// <auto-generated />
using MammalAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MammalAPI.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20200520100246_newmanytoonerelation")]
    partial class newmanytoonerelation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MammalAPI.Models.Family", b =>
                {
                    b.Property<int>("FamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("FamilyId");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("MammalAPI.Models.Habitat", b =>
                {
                    b.Property<int>("HabitatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("HabitatID");

                    b.ToTable("Habitats");
                });

            modelBuilder.Entity("MammalAPI.Models.Mammal", b =>
                {
                    b.Property<int>("MammalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FamilyId")
                        .HasColumnType("int");

                    b.Property<string>("LatinName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<int>("Lifespan")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("MammalId");

                    b.HasIndex("FamilyId");

                    b.ToTable("Mammals");
                });

            modelBuilder.Entity("MammalAPI.Models.MammalHabitat", b =>
                {
                    b.Property<int>("HabitatId")
                        .HasColumnType("int");

                    b.Property<int>("MammalId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("HabitatId", "MammalId");

                    b.HasIndex("MammalId");

                    b.ToTable("MammalHabitats");
                });

            modelBuilder.Entity("MammalAPI.Models.Mammal", b =>
                {
                    b.HasOne("MammalAPI.Models.Family", "Family")
                        .WithMany("Mammals")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MammalAPI.Models.MammalHabitat", b =>
                {
                    b.HasOne("MammalAPI.Models.Habitat", "Habitat")
                        .WithMany("MammalHabitats")
                        .HasForeignKey("HabitatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MammalAPI.Models.Mammal", "Mammal")
                        .WithMany("MammalHabitats")
                        .HasForeignKey("MammalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
